# Generated by Django 4.2.6 on 2024-07-19 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Partner', 'Partner'), ('Customer', 'Customer'), ('Academia', 'Academia')], max_length=50)),
                ('deployment_type', models.CharField(choices=[('SaaS', 'SaaS'), ('PaaS', 'PaaS'), ('On Premises', 'On Premises')], max_length=50)),
                ('tenant_name', models.CharField(max_length=255)),
                ('license_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=50)),
                ('license_valid_from', models.DateField()),
                ('license_valid_till', models.DateField()),
                ('assigned_license_quantity', models.IntegerField()),
                ('approved_by', models.CharField(max_length=255)),
                ('account_manager', models.CharField(max_length=255)),
                ('instance', models.CharField(choices=[('Partner', 'Partner'), ('Sense', 'Sense'), ('Datalabs', 'Datalabs'), ('Inspire', 'Inspire')], max_length=50)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=255)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='license_app.license')),
            ],
        ),
    ]
