# Generated by Django 4.2.6 on 2024-07-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='license_category',
            field=models.CharField(choices=[('Sponsored', 'Sponsored'), ('Free', 'Free'), ('Paid', 'Paid')], default='Free', max_length=50),
        ),
    ]
