# Generated by Django 4.2.6 on 2024-07-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_app', '0002_license_license_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='license_provided',
            field=models.EmailField(choices=[('Platform', 'Platform'), ('Rubisight-Designer', 'Rubisight-Designer'), ('Rubisight-Designer+Rubisight-viewer', 'Rubisight-Designer+Rubisight-viewer'), ('Rubiflow+Rubisight-Designer+Rubisight-viewer', 'Rubiflow+Rubisight-Designer+Rubisight-viewer')], default='Rubiflow+Rubisight-Designer+Rubisight-viewer', max_length=254),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
    ]
