# Generated by Django 4.2.6 on 2024-07-29 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('license_app', '0003_license_license_provided_alter_tenantuser_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='license_provided',
        ),
        migrations.AlterField(
            model_name='license',
            name='deployment_type',
            field=models.CharField(choices=[('SaaS', 'SaaS'), ('PaaS', 'PaaS'), ('On Premises', 'On Premises'), ('Desktop', 'Desktop')], max_length=50),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Rubisight Designer', 'Rubisight Designer'), ('Rubisight Viewer', 'Rubisight Viewer'), ('Rubistudio', 'Rubistudio'), ('RubiFlow', 'RubiFlow'), ('News Analysis', 'News Analysis'), ('Admin', 'Admin'), ('Rubithings', 'Rubithings')], max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='license_app.license')),
            ],
        ),
    ]
