# Generated by Django 4.2.6 on 2024-07-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_app', '0004_remove_license_license_provided_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='license_provided',
            field=models.EmailField(choices=[('Platform', 'Platform'), ('Rubisight-Designer', 'Rubisight-Designer'), ('Rubisight-Designer+Rubisight-viewer', 'Rubisight-Designer+Rubisight-viewer'), ('Rubiflow+Rubisight-Designer+Rubisight-viewer', 'Rubiflow+Rubisight-Designer+Rubisight-viewer')], default='Rubiflow+Rubisight-Designer+Rubisight-viewer', max_length=254),
        ),
        migrations.AlterField(
            model_name='license',
            name='deployment_type',
            field=models.CharField(choices=[('SaaS', 'SaaS'), ('PaaS', 'PaaS'), ('On Premises', 'On Premises')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
