# Generated by Django 4.2.6 on 2024-07-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_app', '0006_license_tenant_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_provided',
            field=models.CharField(choices=[('Platform', 'Platform'), ('Rubisight-Designer', 'Rubisight-Designer'), ('Rubisight-Designer+Rubisight-viewer', 'Rubisight-Designer+Rubisight-viewer'), ('Rubiflow+Rubisight-Designer+Rubisight-viewer', 'Rubiflow+Rubisight-Designer+Rubisight-viewer')], default='Rubiflow+Rubisight-Designer+Rubisight-viewer'),
        ),
    ]
