# Generated by Django 4.2.6 on 2024-07-29 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('license_app', '0007_alter_license_license_provided'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(choices=[('Rubiflow', 'Rubiflow'), ('Rubisight-Designer', 'Rubisight-Designer'), ('Rubistudio', 'Rubistudio'), ('Rubisight-Viewer', 'Rubisight-Viewer')], max_length=50)),
                ('quantity', models.IntegerField()),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='license_app.license')),
            ],
        ),
    ]
